/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.prova3.view;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import poo.prova3.model.Atleta;
import poo.prova3.model.AtletaBasquete;
import poo.prova3.model.AtletaVolei;
import poo.prova3.model.ImportadorAtletas;
import poo.prova3.model.OrdenarPorDesempenho;

/**
 *
 * @author lgonascimento
 */
public class TelaPrincipal extends javax.swing.JFrame {
        protected Atleta atleta;
        protected ImportadorAtletas importador;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnCarregarArquivo = new javax.swing.JButton();
        jBtnExibirMaisJovem = new javax.swing.JButton();
        jBtnExibirMelhorDesempenho = new javax.swing.JButton();
        jBtnListaPorIdade = new javax.swing.JButton();
        jBtnListarPorDesempenho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnCarregarArquivo.setText("Carregar Arquivo");
        jBtnCarregarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCarregarArquivoActionPerformed(evt);
            }
        });

        jBtnExibirMaisJovem.setText("Exibir Mais Jovem");
        jBtnExibirMaisJovem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExibirMaisJovemActionPerformed(evt);
            }
        });

        jBtnExibirMelhorDesempenho.setText("Exibir Melhor Desempenho");
        jBtnExibirMelhorDesempenho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExibirMelhorDesempenhoActionPerformed(evt);
            }
        });

        jBtnListaPorIdade.setText("Listar por Idade");
        jBtnListaPorIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListaPorIdadeActionPerformed(evt);
            }
        });

        jBtnListarPorDesempenho.setText("Listar por Desempenho");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnExibirMaisJovem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnExibirMelhorDesempenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnCarregarArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnListaPorIdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnListarPorDesempenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jBtnCarregarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnExibirMaisJovem)
                .addGap(18, 18, 18)
                .addComponent(jBtnExibirMelhorDesempenho)
                .addGap(18, 18, 18)
                .addComponent(jBtnListaPorIdade)
                .addGap(18, 18, 18)
                .addComponent(jBtnListarPorDesempenho)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnListaPorIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListaPorIdadeActionPerformed
        // TODO add your handling code here:
        System.out.println(importador.getAtletas().indexOf(0));
    }//GEN-LAST:event_jBtnListaPorIdadeActionPerformed

    private void jBtnExibirMelhorDesempenhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExibirMelhorDesempenhoActionPerformed
        // TODO add your handling code here:
         ExibirMelhorDesempenho tela = new ExibirMelhorDesempenho(this,true);
         tela.setVisible(true);
    }//GEN-LAST:event_jBtnExibirMelhorDesempenhoActionPerformed

    private void jBtnExibirMaisJovemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExibirMaisJovemActionPerformed
        // TODO add your handling code here:
        ExibirMaisJovem tela = new ExibirMaisJovem(this,true);
        tela.setVisible(true);
       //importador.sort(new OrdenarPorDesempenho());
    }//GEN-LAST:event_jBtnExibirMaisJovemActionPerformed

    private void jBtnCarregarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCarregarArquivoActionPerformed
         FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("Selecione um arquivo csv", "csv");
        // criamos um objeto de FileChooser
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(fileFilter);

        // Aqui a janela eh aberta como um JOptionPane
        int retorno = chooser.showOpenDialog(null);
        
        if (retorno == JFileChooser.APPROVE_OPTION) { // se o usuario clicou em conrfirmar    
            System.out.println(chooser.getSelectedFile().getAbsolutePath()); // mostra o caminho do arquivo selecionado
        }
        File arquivoCsv =  new File(chooser.getSelectedFile().getAbsolutePath());
        
        try {
        ImportadorAtletas importar = new ImportadorAtletas(chooser.getSelectedFile().getAbsolutePath());
            String linhasDoArquivo = "";
            Scanner scan = new Scanner(new InputStreamReader(new FileInputStream(arquivoCsv), "UTF-8"));
            
            while(scan.hasNext()) {
                linhasDoArquivo = scan.nextLine();
                String[] valorEntreVirgulas = linhasDoArquivo.split(",");
                
                if(valorEntreVirgulas[0].equals("V")) {
                    int idade = Integer.parseInt(valorEntreVirgulas[2]);
                    double saque  = Double.parseDouble(valorEntreVirgulas[3]);
                    double bloqueio = Double.parseDouble(valorEntreVirgulas[4]);
                    double ataque = Double.parseDouble(valorEntreVirgulas[5]);
                    Atleta atletasVolei = new AtletaVolei(valorEntreVirgulas[1], idade, saque, bloqueio, ataque);
                    importar.incluirAtleta(atletasVolei);
                }
                
                if(valorEntreVirgulas[0].equals("B")) {
                    int idade = Integer.parseInt(valorEntreVirgulas[2]);
                    int pontos  = Integer.parseInt(valorEntreVirgulas[3]);
                    int rebotes = Integer.parseInt(valorEntreVirgulas[4]);
                    Atleta atletasBasquete = new AtletaBasquete(valorEntreVirgulas[1], idade, pontos, rebotes);
                    importar.incluirAtleta(atletasBasquete);
                }
                
                
            }
            
        }catch(FileNotFoundException ex) {
            ex.printStackTrace();
            System.out.println(ex.getMessage());
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jBtnCarregarArquivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCarregarArquivo;
    private javax.swing.JButton jBtnExibirMaisJovem;
    private javax.swing.JButton jBtnExibirMelhorDesempenho;
    private javax.swing.JButton jBtnListaPorIdade;
    private javax.swing.JButton jBtnListarPorDesempenho;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
