/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Questao02;

/**
 *
 * @author lgonascimento
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
         jCbSobreEixoX.setEnabled(false);
         jCbSobreEixoY.setEnabled(false);
         jCb1Quadrante.setEnabled(false);
         jCb2Quadrante.setEnabled(false);
         jCb3Quadrante.setEnabled(false);
         jCb4Quadrante.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTfdValorEixoX = new javax.swing.JTextField();
        jTfdValorEixoY = new javax.swing.JTextField();
        jBtnAvaliar = new javax.swing.JButton();
        jCb2Quadrante = new javax.swing.JCheckBox();
        jCbSobreEixoX = new javax.swing.JCheckBox();
        jCbSobreEixoY = new javax.swing.JCheckBox();
        jCb1Quadrante = new javax.swing.JCheckBox();
        jCb4Quadrante = new javax.swing.JCheckBox();
        jCb3Quadrante = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eixo X: ");

        jLabel2.setText("Eixo Y: ");

        jTfdValorEixoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfdValorEixoXActionPerformed(evt);
            }
        });

        jTfdValorEixoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfdValorEixoYActionPerformed(evt);
            }
        });

        jBtnAvaliar.setText("Avaliar");
        jBtnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAvaliarActionPerformed(evt);
            }
        });

        jCb2Quadrante.setText("No 2 Quadrante");
        jCb2Quadrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb2QuadranteActionPerformed(evt);
            }
        });

        jCbSobreEixoX.setText("Incide sobre o Eixo X");
        jCbSobreEixoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbSobreEixoXActionPerformed(evt);
            }
        });

        jCbSobreEixoY.setText("Incide sobre o Eixo Y");
        jCbSobreEixoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbSobreEixoYActionPerformed(evt);
            }
        });

        jCb1Quadrante.setText("No 1 Quadrante");
        jCb1Quadrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb1QuadranteActionPerformed(evt);
            }
        });

        jCb4Quadrante.setText("No 4 Quadrante");
        jCb4Quadrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb4QuadranteActionPerformed(evt);
            }
        });

        jCb3Quadrante.setText("No 3 Quadrante");
        jCb3Quadrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb3QuadranteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCb3Quadrante)
                    .addComponent(jCb4Quadrante)
                    .addComponent(jCb1Quadrante)
                    .addComponent(jCbSobreEixoY)
                    .addComponent(jCbSobreEixoX)
                    .addComponent(jCb2Quadrante)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTfdValorEixoY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTfdValorEixoX, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jBtnAvaliar)))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTfdValorEixoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jBtnAvaliar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTfdValorEixoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jCbSobreEixoX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbSobreEixoY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCb1Quadrante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCb2Quadrante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCb3Quadrante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCb4Quadrante)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAvaliarActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(jTfdValorEixoX.getText());
        int y = Integer.parseInt(jTfdValorEixoY.getText());
        
        Ponto ponto = new Ponto();
        
        ponto.setX(x);
        ponto.setY(y);
        
        
        if(() && (ponto.estaIncidindoSobreX() == true)) {
            
            jCbSobreEixoX.setSelected(true);
            
        }else if(ponto.identificarQuadrante().equals() && (ponto.estaIncidindoSobreY() == true)){
        
            jCbSobreEixoY.setSelected(true);
        
        }
        
    }//GEN-LAST:event_jBtnAvaliarActionPerformed

    private void jCbSobreEixoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbSobreEixoXActionPerformed
            // TODO add your handling code here:
           
    }//GEN-LAST:event_jCbSobreEixoXActionPerformed

    private void jCb2QuadranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb2QuadranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb2QuadranteActionPerformed

    private void jCbSobreEixoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbSobreEixoYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbSobreEixoYActionPerformed

    private void jCb1QuadranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb1QuadranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb1QuadranteActionPerformed

    private void jCb4QuadranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb4QuadranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb4QuadranteActionPerformed

    private void jCb3QuadranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb3QuadranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb3QuadranteActionPerformed

    private void jTfdValorEixoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfdValorEixoXActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_jTfdValorEixoXActionPerformed

    private void jTfdValorEixoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfdValorEixoYActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTfdValorEixoYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAvaliar;
    private javax.swing.JCheckBox jCb1Quadrante;
    private javax.swing.JCheckBox jCb2Quadrante;
    private javax.swing.JCheckBox jCb3Quadrante;
    private javax.swing.JCheckBox jCb4Quadrante;
    private javax.swing.JCheckBox jCbSobreEixoX;
    private javax.swing.JCheckBox jCbSobreEixoY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTfdValorEixoX;
    private javax.swing.JTextField jTfdValorEixoY;
    // End of variables declaration//GEN-END:variables
}
